/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hifly_englishexam_Native */

#ifndef _Included_com_hifly_englishexam_Native
#define _Included_com_hifly_englishexam_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hifly_englishexam_Native
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hifly_englishexam_Native_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
